baseURL: "https://maghfiraer.github.io/" 
title: Maghfira Ramadhani
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: maghfiraEr

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: Teaching
          url: /teaching/
          weight: 2
#        - name: Blog
#          url: /blog/
#          weight: 3
        - name: CV
          url: /cv_afi.pdf
#          weight: 4
#        - name: Tags
#          url: /tags/
#          weight: 4

params:
    description: "Welcome to my personal website!"
    author: Maghfira Ramadhani
    googleAnalyticsID: "G-LG3FT0FV6E"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Maghfira Ramadhani
          subtitle: "Welcome to my personal website! You can call me Afi. I am a PhD student at Georgia Institute of Technology, [School of Economics](https://econ.gatech.edu).\n <br> &nbsp; \n\n My research interests are in energy and environmental economics and applied microeconomics."
          imageUrl: "/picture.jpg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Maghfira Ramadhani
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
#            - name: Blog
#              url: /blog/ 
            - name: CV
              url: "/cv_afi.pdf"
    socialIcons:
#        - name: CV
#          url: "/cv_afi.pdf"
        - name: Email
          url: "mailto:maghfira.ramadhani@gatech.edu"
#        - name: Location
#          url: /location/
        - name: Office Hours
          url: "https://outlook.office.com/bookwithme/user/951a0a27d4b04de1960b5a3481e0d4cf@gatech.edu/meetingtype/t9eSIZ7dVUSyzF4QUMPTgA2?anonymous&ep=mLinkFromTile"
        - name: Google Scholar
          url: "https://scholar.google.com/citations?user=bpN8RCUAAAAJ"
        - name: GitHub
          url: "https://github.com/maghfiraer"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Maghfira Ramadhani"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
